#mongodb config
spring:
  data:
    mongodb:
      host: 192.168.200.20
      port: 27017
      database: fields
    kafka:
      producer:
        bootstrap-servers: 192.168.200.30:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer

#management config
management:
  server:
    port: 10000
  endpoints:
    web:
      exposure:
        include: "*"

#server config
server:
  port: 10000