version: '3'

services:
  consumer:
    image: 'alsvinicius/clients-fields-consumer'
    ports:
      - '21000:20000'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    logging:
      driver: json-file
    networks:
      - clients-fields-network
    deploy:
        placement:
            constraints:
                - node.role == manager
  front:
    image: 'alsvinicius/fields-front-end'
    ports:
      - '3001:80'
    logging:
      driver: json-file
    networks:
      - clients-fields-network
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
            max_attempts: 3
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/alsvinicius
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - clients-fields-network
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
            max_attempts: 3
  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    volumes:
      - kafka_data:/alsvinicius
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=net:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://net:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - clients-fields-network
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/alsvinicius
    networks:
      - clients-fields-network
  api:
    image: 'alsvinicius/clients-fields-api'
    ports:
      - '11000:10000'
    volumes:
      - api_data:/alsvinicius
    logging:
      driver: json-file
    networks:
      - clients-fields-network
    deploy:
        replicas: 2
        restart_policy:
            condition: on-failure
            max_attempts: 3
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongo_data:
    driver: local
  api_data:
    driver: local
  front_data:
    driver: local
  consumer_data:
    driver: local
   
networks:
  clients-fields-network:
    external: true